server:
  port: 10086
spring:
  application:
    name: oshop-registry
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: false  #不注册自身
    fetch-registry: true  #是否拉去服务列表